### PR TITLE
Fix a small markup error in the cyw43 documentation.

### PR DESCRIPTION
**Pull request by pkoning2**

### CODE REVIEW

**Comment by tabemann** [comment]
On Tue, Mar 5, 2024 at 12:53 PM Paul Koning ***@***.***>
wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/tabemann/zeptoforth/pull/95
> Commit Summary
>
>    - 8164559
>    <https://github.com/tabemann/zeptoforth/pull/95/commits/8164559577cad8747947d3902630385dcb05f4fe>
>    Fix a small markup error in the cyw43 documentation.
>
> File Changes
>
> (1 file <https://github.com/tabemann/zeptoforth/pull/95/files>)
>
>    - *M* docs/extra/cyw43.md
>    <https://github.com/tabemann/zeptoforth/pull/95/files#diff-d3e30290844c02bcc21061fafc5a860ab2fbb9e3605d58bf7b7d978110b35775>
>    (2)
>
> Patch Links:
>
>    - https://github.com/tabemann/zeptoforth/pull/95.patch
>    - https://github.com/tabemann/zeptoforth/pull/95.diff
>
> You really are better at finding stuff like this than I am! (In this case
I probably never looked at the rendered doc myself, hence my missing th is.)

Travis

**Comment by pkoning2** [comment]
Not knowing things means I have to read the docs... :-)

**Comment by tabemann** [comment]
Well I do sometimes look at the docs, but I generally read them in their original Markdown, which makes it easier to miss things like this.

**Comment by pkoning2** [comment]
When I forget my Markdown or want to double-check what I did, this little [MD editor](http://markdown.pioul.fr/) works nicely.

**Pull request merged**
